export { LandingPage } from './LandingPage'
export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'
export { OAuthSuccessPage } from './OAuthSuccessPage' // 🟡 OAuth integration
export { VerifyEmailPage } from './VerifyEmailPage'
export { ForgotPasswordPage } from './ForgotPasswordPage'
export { ResetPasswordPage } from './ResetPasswordPage'
export { DashboardPage } from './DashboardPage'
export { ProfilePage } from './ProfilePage'
export { ResumeUploadPage } from './ResumeUploadPage'
export { ResumeListPage } from './ResumeListPage'
export { ResumeAnalysisPage } from './ResumeAnalysisPage'
export { ResumeComparisonPage } from './ResumeComparisonPage'
export { CoverLetterPage } from './CoverLetterPage'
export { CoverLetterListPage } from './CoverLetterListPage'
export { CoverLetterAnalyticsPage } from './CoverLetterAnalyticsPage'
export { AdminPage } from './AdminPage'
